jtrackseries-postgresql:
  container_name: jtrackseries-postgresql
  image: postgres:9.4.5
  # volumes:
  #   - ~/volumes/jhipster/JTrackSeries/postgresql/:/var/lib/postgresql/
  environment:
    - POSTGRES_USER=JTrackSeries
    - POSTGRES_PASSWORD=
  ports:
    - "5432:5432"
